### ISSUE TITLE
Upload Content S3 task fails with the exception of no signature of method. 

### ISSUE THREAD

**Issue by sandeeprao** [classmethod-aws/gradle-aws-plugin#14]
Hi,

uploadContent task is failing with the following exception. 

No signature of method: com.amazonaws.services.s3.AmazonS3Client.getResourceUrl() is applicable for argument types: (java.lang.String, java.lang.String, com.amazonaws.services.s3.model.ObjectMetadata) values: [ldswarehouse, jar/, com.amazonaws.services.s3.model.ObjectMetadata@c021e20]
Possible solutions: getResourceUrl(java.lang.String, java.lang.String)
	at jp.classmethod.aws.gradle.s3.AmazonS3FileUploadTask.upload(AmazonS3FileUploadTask.groovy:58)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 69 more

**Comment by miyamoto-daisuke** [comment]
Can you please try latest version (currently 0.18.1) and let me know if this is solved?

**Comment by miyamoto-daisuke** [comment]
If this problem is still occur in the latest version, please reopen this issue.
