### ISSUE TITLE
Sync Task fails with MissingMethodException

### ISSUE THREAD

**Issue by izreal** [classmethod-aws/gradle-aws-plugin#8]
It appears that an extra (null) parameter is being passed into the putObject() method.

````
Caused by: groovy.lang.MissingMethodException: No signature of method: com.amazonaws.services.s3.AmazonS3Client.putObject() is applicable for argument types: (java.lang.String, java.lang.String, java.io.File, null) values: [my-bucket-name, some/bucket/prefix/path/my-file.jar, /my/local/folder/pathmy-file.jar, ...]
Possible solutions: putObject(java.lang.String, java.lang.String, java.io.File), putObject(java.lang.String, java.lang.String, java.io.InputStream, com.amazonaws.services.s3.model.ObjectMetadata), getObject(java.lang.String, java.lang.String), putObject(com.amazonaws.services.s3.model.PutObjectRequest), getObject(com.amazonaws.services.s3.model.GetObjectRequest, java.io.File)
	at jp.classmethod.aws.gradle.s3.SyncTask$_upload_closure1.doCall(SyncTask.groovy:91)
	at com.sun.proxy.$Proxy45.visitFile(Unknown Source)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:157)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visitFrom(DirectoryFileTree.java:125)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visit(DirectoryFileTree.java:115)
	at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:96)
	at org.gradle.api.internal.file.AbstractFileTree.visit(AbstractFileTree.java:113)
	at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:47)
	at org.gradle.api.file.FileTree$visit.call(Unknown Source)
	at jp.classmethod.aws.gradle.s3.SyncTask.upload(SyncTask.groovy:62)
	at jp.classmethod.aws.gradle.s3.SyncTask.this$4$upload(SyncTask.groovy)
	at jp.classmethod.aws.gradle.s3.SyncTask$this$4$upload.callCurrent(Unknown Source)
	at jp.classmethod.aws.gradle.s3.SyncTask.uploadAction(SyncTask.groovy:52)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more
````

**Comment by miyamoto-daisuke** [comment]
This issue is fixed at v0.14.1.
The latest version is v0.14.2.  Try out
